// Auto Generated
const GROUP_TO_ANSWERS = {
  Anuradhapura: [
    "Anuradhapura East",
    "Anuradhapura West",
    "Horowpothana",
    "Kalawewa",
    "Kekirawa",
    "Medawachchiya",
    "Mihinthale",
  ],
  Badulla: [
    "Badulla",
    "Bandarawela",
    "Hali Ela",
    "Haputale",
    "Mahiyanganaya",
    "Passara",
    "Uva Paranagama",
    "Viyaluwa",
    "Welimada",
  ],
  Colombo: [
    "Avissawella",
    "Borella",
    "Colombo Central",
    "Colombo East",
    "Colombo North",
    "Colombo West",
    "Dehiwala",
    "Homagama",
    "Kaduwela",
    "Kesbewa",
    "Kolonnawa",
    "Kotte",
    "Maharagama",
    "Moratuwa",
    "Ratmalana",
  ],
  Digamadulla: ["Ampara", "Kalmunai", "Pothuvil", "Samanthurai"],
  Galle: [
    "Akmeemana",
    "Ambalangoda",
    "Baddegama",
    "Balapitiya",
    "Bentara Elpitiya",
    "Galle",
    "Habaraduwa",
    "Hiniduma",
    "Karandeniya",
    "Ratgama",
  ],
  Gampaha: [
    "Attanagalla",
    "Biyagama",
    "Divulapitiya",
    "Dompe",
    "Gampaha",
    "Ja Ela",
    "Katana",
    "Kelaniya",
    "Mahara",
    "Minuwangoda",
    "Mirigama",
    "Negombo",
    "Wattala",
  ],
  Hambantota: ["Beliatta", "Mulkirigala", "Tangalle", "Thissamaharama"],
  Jaffna: [
    "Chavakachcheri",
    "Jaffna",
    "Kankesanthurai",
    "Kayts",
    "Kilinochchi",
    "Kopay",
    "Manipay",
    "Nallur",
    "Point Pedro",
    "Udupiddy",
    "Vaddukoddai",
  ],
  Kalutara: [
    "Agalawatta",
    "Bandaragama",
    "Beruwala",
    "Bulathsinhala",
    "Horana",
    "Kalutara",
    "Mathugama",
    "Panadura",
  ],
  Kandy: [
    "Galagedara",
    "Gampola",
    "Harispattuwa",
    "Hewaheta",
    "Kundasale",
    "Mahanuwara",
    "Nawalapitiya",
    "Pathadumbara",
    "Senkadagala",
    "Teldeniya",
    "Ududumbara",
    "Udunuwara",
    "Yatinuwara",
  ],
  Kegalle: [
    "Aranayaka",
    "Dedigama",
    "Deraniyagala",
    "Galigamuwa",
    "Kegalle",
    "Mawanella",
    "Rambukkana",
    "Ruwanwella",
    "Yatiyanthota",
  ],
  Kurunegala: [
    "Bingiriya",
    "Dambadeniya",
    "Dodangaslanda",
    "Galgamuwa",
    "Hiriyala",
    "Katugampola",
    "Kuliyapitiya",
    "Kurunegala",
    "Mawathagama",
    "Nikaweratiya",
    "Panduwasnuwara",
    "Polgahawela",
    "Wariyapola",
    "Yapahuwa",
  ],
  Matale: ["Dambulla", "Laggala", "Matale", "Rattota"],
  Matara: [
    "Akuressa",
    "Deniyaya",
    "Devinuwara",
    "Hakmana",
    "Kamburupitiya",
    "Matara",
    "Weligama",
  ],
  "Nuwara-Eliya": [
    "Hanguranketha",
    "Kothmale",
    "Nuwara Eliya Maskeliya",
    "Walapane",
  ],
  Puttalam: ["Anamaduwa", "Chilaw", "Nattandiya", "Puttalam", "Wennappuwa"],
  Ratnapura: [
    "Balangoda",
    "Eheliyagoda",
    "Kalawana",
    "Kolonna",
    "Nivithigala",
    "Pelmadulla",
    "Rakwana",
    "Ratnapura",
  ],
};
export default GROUP_TO_ANSWERS;
